[2022-07-12 18:17:25,896] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.convert_to_csv manual__2022-07-12T18:17:13.935486+00:00 [queued]>
[2022-07-12 18:17:25,911] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.convert_to_csv manual__2022-07-12T18:17:13.935486+00:00 [queued]>
[2022-07-12 18:17:25,911] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 18:17:25,911] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-12 18:17:25,911] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 18:17:25,931] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): convert_to_csv> on 2022-07-12 18:17:13.935486+00:00
[2022-07-12 18:17:25,936] {standard_task_runner.py:52} INFO - Started process 288 to run task
[2022-07-12 18:17:25,940] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_ingestion_local', 'convert_to_csv', 'manual__2022-07-12T18:17:13.935486+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local_dag.py', '--cfg-path', '/tmp/tmpurp3sgam', '--error-file', '/tmp/tmp0cscdgff']
[2022-07-12 18:17:25,943] {standard_task_runner.py:80} INFO - Job 3: Subtask convert_to_csv
[2022-07-12 18:17:26,031] {task_command.py:371} INFO - Running <TaskInstance: data_ingestion_local.convert_to_csv manual__2022-07-12T18:17:13.935486+00:00 [running]> on host dfccf9ac7c75
[2022-07-12 18:17:26,097] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-07-12 18:17:26,153] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_ingestion_local
AIRFLOW_CTX_TASK_ID=convert_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T18:17:13.935486+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T18:17:13.935486+00:00
[2022-07-12 18:17:26,281] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_local_dag.py", line 28, in convert_to_csv_callable
    .config("spark.some.config.option", "some-value") \
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 195, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 417, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 106, in launch_gateway
    raise RuntimeError("Java gateway process exited before sending its port number")
RuntimeError: Java gateway process exited before sending its port number
[2022-07-12 18:17:26,297] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_local, task_id=convert_to_csv, execution_date=20220712T181713, start_date=20220712T181725, end_date=20220712T181726
[2022-07-12 18:17:26,315] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task convert_to_csv (Java gateway process exited before sending its port number; 288)
[2022-07-12 18:17:26,351] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 18:17:26,412] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
