[2022-07-12 17:45:25,049] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.convert_to_csv manual__2022-07-12T17:45:13.518750+00:00 [queued]>
[2022-07-12 17:45:25,070] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.convert_to_csv manual__2022-07-12T17:45:13.518750+00:00 [queued]>
[2022-07-12 17:45:25,070] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 17:45:25,070] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-12 17:45:25,071] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 17:45:25,100] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): convert_to_csv> on 2022-07-12 17:45:13.518750+00:00
[2022-07-12 17:45:25,107] {standard_task_runner.py:52} INFO - Started process 233 to run task
[2022-07-12 17:45:25,111] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_ingestion_local', 'convert_to_csv', 'manual__2022-07-12T17:45:13.518750+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local_dag.py', '--cfg-path', '/tmp/tmpf9e6odnu', '--error-file', '/tmp/tmpcwkpjc1j']
[2022-07-12 17:45:25,113] {standard_task_runner.py:80} INFO - Job 3: Subtask convert_to_csv
[2022-07-12 17:45:25,218] {task_command.py:371} INFO - Running <TaskInstance: data_ingestion_local.convert_to_csv manual__2022-07-12T17:45:13.518750+00:00 [running]> on host 9104b9631019
[2022-07-12 17:45:25,303] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-07-12 17:45:25,393] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_ingestion_local
AIRFLOW_CTX_TASK_ID=convert_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T17:45:13.518750+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T17:45:13.518750+00:00
[2022-07-12 17:45:25,396] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_local_dag.py", line 25, in convert_to_csv_callable
    df = spark.read.format("parquet").load(file_name)
AttributeError: module 'spark' has no attribute 'read'
[2022-07-12 17:45:25,411] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_local, task_id=convert_to_csv, execution_date=20220712T174513, start_date=20220712T174525, end_date=20220712T174525
[2022-07-12 17:45:25,435] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task convert_to_csv (module 'spark' has no attribute 'read'; 233)
[2022-07-12 17:45:25,484] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 17:45:25,560] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
