[2022-07-12 10:30:51,798] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.download manual__2022-07-12T10:30:50.233404+00:00 [queued]>
[2022-07-12 10:30:51,815] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.download manual__2022-07-12T10:30:50.233404+00:00 [queued]>
[2022-07-12 10:30:51,815] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 10:30:51,815] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-07-12 10:30:51,815] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 10:30:51,831] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download> on 2022-07-12 10:30:50.233404+00:00
[2022-07-12 10:30:51,838] {standard_task_runner.py:52} INFO - Started process 5335 to run task
[2022-07-12 10:30:51,842] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_local', 'download', 'manual__2022-07-12T10:30:50.233404+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local_dag.py', '--cfg-path', '/tmp/tmp_ey4qh_v', '--error-file', '/tmp/tmp63xeyqz4']
[2022-07-12 10:30:51,843] {standard_task_runner.py:77} INFO - Job 12: Subtask download
[2022-07-12 10:30:51,921] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_local.download manual__2022-07-12T10:30:50.233404+00:00 [running]> on host aff450fe4e0f
[2022-07-12 10:30:52,001] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-07-12 10:30:52,001] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1418, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1992, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1113, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 268, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 263, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 349, in call
    return __obj(*args, **kwargs)
TypeError: 'months' is an invalid keyword argument for __new__()
[2022-07-12 10:30:52,027] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_local, task_id=download, execution_date=20220712T103050, start_date=20220712T103051, end_date=20220712T103052
[2022-07-12 10:30:52,040] {standard_task_runner.py:92} ERROR - Failed to execute job 12 for task download
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1418, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1992, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1113, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 268, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 263, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 349, in call
    return __obj(*args, **kwargs)
TypeError: 'months' is an invalid keyword argument for __new__()
[2022-07-12 10:30:52,059] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-12 10:30:52,099] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
