[2022-07-12 20:25:00,536] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:24:46.408892+00:00 [queued]>
[2022-07-12 20:25:00,561] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:24:46.408892+00:00 [queued]>
[2022-07-12 20:25:00,561] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 20:25:00,561] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-12 20:25:00,562] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 20:25:00,597] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): ingest_data> on 2022-07-12 20:24:46.408892+00:00
[2022-07-12 20:25:00,610] {standard_task_runner.py:52} INFO - Started process 1443 to run task
[2022-07-12 20:25:00,624] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_ingestion_local', 'ingest_data', 'manual__2022-07-12T20:24:46.408892+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local_dag.py', '--cfg-path', '/tmp/tmpxwobdgza', '--error-file', '/tmp/tmpnrrw_q10']
[2022-07-12 20:25:00,625] {standard_task_runner.py:80} INFO - Job 30: Subtask ingest_data
[2022-07-12 20:25:00,793] {task_command.py:371} INFO - Running <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:24:46.408892+00:00 [running]> on host 139e0ae5bdf5
[2022-07-12 20:25:00,900] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-07-12 20:25:01,005] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_ingestion_local
AIRFLOW_CTX_TASK_ID=ingest_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T20:24:46.408892+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T20:24:46.408892+00:00
[2022-07-12 20:25:01,010] {logging_mixin.py:115} INFO - *** *** pgdatabase 5432 ny_taxi yellow_taxi_2022_04 /opt/airflow/output_2022-04.parquet
[2022-07-12 20:25:01,010] {logging_mixin.py:115} INFO - user is ***
[2022-07-12 20:25:02,650] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data.py", line 20, in ingest_callable
    df.to_csv(csv_file, index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '/opt/airflow/output_2022-04.csv'
[2022-07-12 20:25:02,687] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_local, task_id=ingest_data, execution_date=20220712T202446, start_date=20220712T202500, end_date=20220712T202502
[2022-07-12 20:25:02,758] {standard_task_runner.py:97} ERROR - Failed to execute job 30 for task ingest_data ([Errno 21] Is a directory: '/opt/airflow/output_2022-04.csv'; 1443)
[2022-07-12 20:25:02,980] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 20:25:03,066] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
