[2022-07-12 20:13:41,780] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:13:27.028144+00:00 [queued]>
[2022-07-12 20:13:41,803] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:13:27.028144+00:00 [queued]>
[2022-07-12 20:13:41,804] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 20:13:41,804] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-12 20:13:41,804] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 20:13:41,836] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): ingest_data> on 2022-07-12 20:13:27.028144+00:00
[2022-07-12 20:13:41,846] {standard_task_runner.py:52} INFO - Started process 613 to run task
[2022-07-12 20:13:41,850] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_ingestion_local', 'ingest_data', 'manual__2022-07-12T20:13:27.028144+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local_dag.py', '--cfg-path', '/tmp/tmp1_yhrtr5', '--error-file', '/tmp/tmpwp74o94y']
[2022-07-12 20:13:41,851] {standard_task_runner.py:80} INFO - Job 26: Subtask ingest_data
[2022-07-12 20:13:41,964] {task_command.py:371} INFO - Running <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:13:27.028144+00:00 [running]> on host 139e0ae5bdf5
[2022-07-12 20:13:42,053] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-07-12 20:13:42,141] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_ingestion_local
AIRFLOW_CTX_TASK_ID=ingest_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T20:13:27.028144+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T20:13:27.028144+00:00
[2022-07-12 20:13:42,145] {logging_mixin.py:115} INFO - *** *** pgdatabase 5432 ny_taxi yellow_taxi_2022_04.parquet /opt/airflow/output_2022-04.parquet
[2022-07-12 20:13:42,146] {logging_mixin.py:115} INFO - user is ***
[2022-07-12 20:14:57,059] {logging_mixin.py:115} INFO - yellow_taxi_2022_04.parquet /opt/airflow/output_2022-04.parquet
[2022-07-12 20:14:57,067] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data.py", line 26, in ingest_callable
    df_iter = df.read_csv(csv_file, iterator=True, chunksize=100000)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'read_csv'
[2022-07-12 20:14:57,081] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_local, task_id=ingest_data, execution_date=20220712T201327, start_date=20220712T201341, end_date=20220712T201457
[2022-07-12 20:14:57,096] {standard_task_runner.py:97} ERROR - Failed to execute job 26 for task ingest_data ('DataFrame' object has no attribute 'read_csv'; 613)
[2022-07-12 20:14:57,219] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 20:14:57,263] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
