[2022-07-12 20:19:58,549] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:13:27.028144+00:00 [queued]>
[2022-07-12 20:19:58,561] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:13:27.028144+00:00 [queued]>
[2022-07-12 20:19:58,561] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 20:19:58,561] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-07-12 20:19:58,561] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 20:19:58,578] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): ingest_data> on 2022-07-12 20:13:27.028144+00:00
[2022-07-12 20:19:58,583] {standard_task_runner.py:52} INFO - Started process 1045 to run task
[2022-07-12 20:19:58,586] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_ingestion_local', 'ingest_data', 'manual__2022-07-12T20:13:27.028144+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local_dag.py', '--cfg-path', '/tmp/tmp9xm1rxsr', '--error-file', '/tmp/tmpkbl6ctnk']
[2022-07-12 20:19:58,587] {standard_task_runner.py:80} INFO - Job 27: Subtask ingest_data
[2022-07-12 20:19:58,658] {task_command.py:371} INFO - Running <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:13:27.028144+00:00 [running]> on host 139e0ae5bdf5
[2022-07-12 20:19:58,714] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-07-12 20:19:58,763] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_ingestion_local
AIRFLOW_CTX_TASK_ID=ingest_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T20:13:27.028144+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T20:13:27.028144+00:00
[2022-07-12 20:19:58,764] {logging_mixin.py:115} INFO - *** *** pgdatabase 5432 ny_taxi yellow_taxi_2022_04.parquet /opt/airflow/output_2022-04.parquet
[2022-07-12 20:19:58,764] {logging_mixin.py:115} INFO - user is ***
[2022-07-12 20:20:46,149] {logging_mixin.py:115} INFO - yellow_taxi_2022_04.parquet /opt/airflow/output_2022-04.parquet
[2022-07-12 20:20:46,163] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data.py", line 26, in ingest_callable
    df_iter = pd.read_csv(csv_file, iterator=True, chunksize=100000)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '/opt/airflow/output_2022-04.csv'
[2022-07-12 20:20:46,327] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=data_ingestion_local, task_id=ingest_data, execution_date=20220712T201327, start_date=20220712T201958, end_date=20220712T202046
[2022-07-12 20:20:46,356] {standard_task_runner.py:97} ERROR - Failed to execute job 27 for task ingest_data ([Errno 21] Is a directory: '/opt/airflow/output_2022-04.csv'; 1045)
[2022-07-12 20:20:46,495] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 20:20:46,538] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
